CCDirectLink/crosscode-map-editor

- backend/src/controllers/api.ts
This PR makes the existing backend API more robust, and fixes obscure bugs when giving certain "valid" values to `pathToCrosscode`, by using `path.resolve`(which works around certain OS-specific quirks automatically) instead of concatenating paths manually when listing all files.
> QoL: Use path.resolve instead of manual path concatenation on backend

- backend/tslint.json
This solves an issue where tslint throws an error when you have a long path to CrossCode's assets folder in config.ts (caused by max-line-length)
> Don't tslint config.ts

- webapp/src/app/shared/phaser/tilemap/cc-map-layer.ts
Fixes #67 
Fixed a bug where resizing a layer would override all unsaved tile data of the layer.
> Fixed layer resize overriding unsaved data

- CHANGELOG.md
- webapp/src/app/components/load-map/load-map.component.html
- webapp/src/app/components/load-map/load-map.component.scss
- webapp/src/app/components/load-map/load-map.component.ts
- webapp/src/app/shared/highlight.directive.ts
- webapp/src/app/shared/phaser/entities/cc-entity.ts
- webapp/src/app/shared/shared.module.ts
- webapp/src/app/shared/widgets/abstract-widget.ts
- webapp/src/app/shared/widgets/event-widget/event-editor/add/event-add.component.html
- webapp/src/app/shared/widgets/event-widget/event-editor/add/event-add.component.scss
- webapp/src/app/shared/widgets/event-widget/event-editor/add/event-add.component.ts
- webapp/src/app/shared/widgets/event-widget/event-registry/default-event.ts
- webapp/src/app/shared/widgets/event-widget/event-registry/wait.ts
- webapp/src/app/shared/widgets/string-widget/string-widget.component.ts
- webapp/src/app/shared/widgets/widget.module.ts
- webapp/src/assets/events.json
- webapp/src/styles.scss
Depends on #80
Improves default event by adding a database of all events with the associated attributes. 
The default event reads it and shows all the editable properties in the event editor instead of a single json.
fixes #78
> improved default events

- webapp/src/app/shared/phaser/entities/registry/prop.ts
If a `prop` has `SUB` on `Anims` it seems like all of the `SUB` entries should be displayed. However, this seems to cause some bugs because `renderType: 'lighter'` doesn't seem to work properly.
For now, this PR changes props to draw the first entry which always seems to be the base of the entity.
Example:
> Fixed prop not showing bugs

- CHANGELOG.md
- webapp/src/app/shared/phaser/tilemap/cc-map-layer.ts
- webapp/src/app/tests/layers.spec.ts
- Initialize tiles with 0 instead of -1 in new layers, fixes #165
- Resize and offset should now work properly again
- Fixed: changing layer tileset causes previously made changes to be lost
> Layer bugfix

- .github/actions/build/action.yml
- .github/workflows/build.yml
- .github/workflows/prepare_release.yml
- .github/workflows/pull_request.yml
- .github/workflows/release.yml
- CHANGELOG.md
- builds the project on every push except on master branch
- pull request also run a check to see if the changelog was changed
prepare release:
- is triggered when a pull request is merged and has a label `bump:x`
- changelog is automatically updated
- package.json and package-lock.json version is updated
- a tag for the version is created
- pushes changes to the repo
release:
- is triggered when a new tag is pushed. Can be manually or through the prepare release step
- builds the binaries on linux, mac and windows
- makes a new release with the binaries and appends the changelog to it
------
This pr requires:  
- 3 new labels `bump:major` `bump:minor` `bump:patch`
- a github personal access token with push access to this repo stored as a secret with the name `PAT`
closes #195
> automate release process

- .github/workflows/build.yml
run build on all pull requests so it also includes forked repos (untested, because i don't know how to fork my own fork)
https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662/13
> Allow forked repos to run github actions

- CHANGELOG.md
- webapp/src/app/shared/globals.ts
- webapp/src/app/shared/phaser/entities/entity-manager.ts
- webapp/src/app/shared/phaser/map-pan.ts
- webapp/src/app/shared/phaser/tilemap/tile-drawer.ts
Adds `SHIFT` as a control to pan the camera,  allowing a user working on a touch pad to perform the already existing zoom (ALT + two finger zoom) and what this pull request covers, to pan ( SHIFT + mouse click finger move)
> Add map pan key control

- CHANGELOG.md
- webapp/main.js
According to [this link](https://www.electronjs.org/docs/breaking-changes#default-changed-contextisolation-defaults-to-true) `contextIsolation` will be set to `true` by default in Electron 12 which will remove `require` from the renderer's scope.
This PR sets `contextIsolation` to `false` explicitly to avoid future bugs.
> Set contextIsolation to false for future updates

- CHANGELOG.md
- webapp/src/app/models/events.ts
- webapp/src/app/shared/widgets/event-widget/event-editor/editor/event-editor.component.ts
- webapp/src/app/shared/widgets/event-widget/event-window/event-window.component.ts
- webapp/src/app/shared/widgets/npc-states-widget/npc-states-widget.component.ts
- webapp/src/app/shared/widgets/npc-states-widget/npc-states/npc-states.component.html
- webapp/src/app/shared/widgets/npc-states-widget/npc-states/npc-states.component.scss
- webapp/src/app/shared/widgets/npc-states-widget/npc-states/npc-states.component.ts
Solves #188.
Add the ability to load `shop`, `arena` and `trade` events in the event editor and save them correctly (including `quest` events).
The event type can be specified in the side panel of NPC editing windows:
Trade events add another property below the event type to specify the trader name:
Trade events have a warning that pops up when a trader is not specified:
There is also a warning if a trade event does not have a `START_NPC_TRADE_MENU` event:
The warning does not apper on traders with no events since the `START_NPC_TRADE_MENU` is not required if the trader has its `event` property not set and the editor exports traders with an empty event array as undefined.
> Solve issue 188

- CHANGELOG.md
- webapp/src/app/shared/widgets/event-widget/event-editor/event-helper.service.ts
- webapp/src/app/shared/widgets/event-widget/event-registry/event-registry.service.ts
- webapp/src/app/shared/widgets/event-widget/event-registry/open-quest-dialogue.ts
Solves #223.
Adds branch display to the `OPEN_QUEST_DIALOG` event:
> Add branch display to `OPEN_QUEST_DIALOG` events

- CHANGELOG.md
- webapp/src/app/shared/widgets/event-widget/event-editor/detail/event-detail.component.ts
- webapp/src/app/shared/widgets/event-widget/event-editor/editor/event-editor.component.html
- webapp/src/app/shared/widgets/event-widget/event-editor/editor/event-editor.component.ts
- webapp/src/app/shared/widgets/event-widget/event-editor/event-helper.service.ts
- webapp/src/app/shared/widgets/event-widget/event-registry/event-registry.service.ts
- webapp/src/app/shared/widgets/event-widget/event-registry/start-npc-trade-menu.ts
Adds event branches to the `START_NPC_TRADE_MENU` event:
Toggling the `withBranches` property adds or removes branches:
This PR also fixes `SHOW_CHOICE` branches not updating when the number of choices is changed.
> Add branch display to `START_NPC_TRADE_MENU` events

- CHANGELOG.md
- webapp/src/app/components/widgets/event-widget/event-registry/default-event.ts
- webapp/src/app/components/widgets/event-widget/event-registry/event-registry.service.ts
- webapp/src/app/components/widgets/event-widget/event-registry/show-side-msg.ts
Made SHOW_SIDE_MSG pretty , closes #250
> pretty SHOW_SIDE_MSG

- webapp/src/app/app.module.ts
- webapp/src/app/components/widgets/character-widget/character-widget.component.html
- webapp/src/app/components/widgets/character-widget/character-widget.component.ts
- webapp/src/app/components/widgets/custom-des-type-widget/custom-des-type-widget.component.html
- webapp/src/app/components/widgets/enemy-single-type-widget/enemy-single-type-widget.component.html
- webapp/src/app/components/widgets/enemy-single-type-widget/enemy-single-type-widget.component.ts
- webapp/src/app/components/widgets/inputs/input-with-button/input-with-button.component.html
- webapp/src/app/components/widgets/inputs/input-with-button/input-with-button.component.scss
- webapp/src/app/components/widgets/inputs/input-with-button/input-with-button.component.ts
- webapp/src/app/services/phaser/entities/registry/item-destruct.ts
implemented alternative manual input. 
It's a basic text input with a button at the end to open the image select widget.
I think this is the better approach. It completely avoids opening the image overlay when using known values like before the overlay was a thing
> moved manual input outside of image select widget

- CHANGELOG.md
- webapp/src/app/components/layers/layers.component.html
- webapp/src/app/components/layers/layers.component.ts
- webapp/src/app/services/phaser/tilemap/cc-map-layer.ts
- webapp/src/app/services/phaser/tilemap/cc-map.ts
Adds in support for selecting all the special level types in a layer - specifically `first`, `last`, `light`, `postlight`, `object1`, `object2`, and `object3`. The map editor already has support for loading (and saving) layers with named levels, this merely adds the ability for one to select them (as well as properly displaying them in the layer selector). 
For example, by loading up the map `autumn/path-3-1` in the current version of the map editor, followed by the same map loaded with the new support:
As for the selector for the layer levels:
These changes also follow the current behavior of the map editor - it treats `first` as though it is level 0, and every other level as though it was level 10.
Closes #286 and #157.
> Added support for selecting the special layer levels

- CHANGELOG.md
- common/src/controllers/api.ts
The editor freezes on a while screen when there are JSON syntax errors in one of the mods `package.json`.
Such a mod can still work without problems in CC if it has a `ccmod.json`
> Ignore mod when JSON errors accur in package.json

- CHANGELOG.md
- webapp/src/app/services/phaser/entities/registry/scalable-prop.ts
- webapp/src/app/services/phaser/tilemap/layer-helper.ts
fixes #312
- made "customPutTilesAt" work even if array contains null/undefined
- added default size to scalable prop if it doesn't exist to prevent crashes
> fixed map not loading

- CHANGELOG.md
- webapp/src/app/components/phaser/phaser.component.ts
> Fix window resizing

- CHANGELOG.md
- common/src/controllers/api.ts
- webapp/src/app/app.module.ts
- webapp/src/app/components/dialogs/settings/settings.component.html
- webapp/src/app/components/dialogs/settings/settings.component.ts
- webapp/src/app/components/widgets/event-widget/event-registry/abstract-event.ts
- webapp/src/app/directives/colored-text.directive.ts
- webapp/src/app/services/color.service.ts
- webapp/src/app/services/http-client.service.ts
Closes #323 and also implements proper mod names instead of just directory names
> Support ccmod.json and mod names
