- backend/package-lock.json
- backend/src/controllers/api.ts
- backend/src/server.ts
- webapp/src/app/app.module.ts
- webapp/src/app/components/editor/editor.component.html
- webapp/src/app/components/editor/editor.component.ts
- webapp/src/app/components/phaser/phaser.component.ts
- webapp/src/app/components/tile-selector/tile-selector.component.html
- webapp/src/app/components/tile-selector/tile-selector.component.scss
- webapp/src/app/components/tile-selector/tile-selector.component.ts
- webapp/src/app/models/file-infos.ts
- webapp/src/app/models/tile-selector.ts
- webapp/src/app/services/http-client.service.ts
- webapp/src/app/shared/phaser/tilemap/tile-drawer.ts
The old tile selector that appears when pressing space still works.
> Added tile selector window

- webapp/src/app/components/layers/layers.component.ts
- webapp/src/app/components/tile-selector/tile-selector.component.ts
> Fixed tileselector on new layer

- webapp/src/app/components/phaser/phaser.component.ts
Doesn't break when no layers are supplied.
> Fixed rescaleBorder early return condition

- .travis.yml
- webapp/package.json
* Now tests for compile errors on every commit
* Runs for all platforms
* Adds binaries to releases
Windows builds are marked as allowed to fail because Windows support is still experimental within Travis.
> Improve Travis-CI integration

- webapp/src/app/shared/phaser/map-pan.ts
- webapp/src/typings.d.ts
Contains a workaround for missing typings that should be removed once phaser-ce fixes it.
Fixes #41
> Fixes for zoom

- backend/package-lock.json
- webapp/angular.json
- webapp/tslint.json
Made some fixes for webapp tslint.
> Fixes for webapp tslint

- webapp/main.js
- webapp/package-lock.json
- webapp/package.json
Fixes #51 
Opening a new instance of the map editor now closes the instances and opens a new window in the first instance of the map editor.
May need some testing on Mac.
> Fixed multiple instances causing errors

- README.md
> Added descriptions to readme

- CHANGELOG.md
- webapp/main.js
- webapp/src/app/components/sidenav/sidenav.component.ts
- webapp/src/app/components/tile-selector/tile-selector.component.ts
- webapp/src/app/services/height-map/height-map.service.ts
- webapp/src/app/services/save.service.ts
- webapp/src/app/shared/history/history.component.ts
- webapp/src/app/shared/phaser/entities/entity-manager.ts
- webapp/src/app/shared/phaser/tilemap/cc-map.ts
- webapp/src/app/shared/widgets/event-widget/event-editor/row-text/row-text.component.ts
depends on #97
fixes a bunch of smaller issues
- keep editor mode (layer/entities) after map reload, fixes #89
- added history for Entity create/delete/edit, fixes #88
- added history shortcuts back (ctrl + z, ctrl + shift + z), fixes #77
- hide menu in electron build, because most settings don't work. fixes #93
> fixes some smaller issues

- CHANGELOG.md
- webapp/src/app/components/layers/layers.component.ts
- webapp/src/app/components/tile-selector/tile-selector.scene.ts
- webapp/src/app/shared/phaser/entities/cc-entity.ts
- webapp/src/app/shared/phaser/entities/registry/item-destruct.ts
- webapp/src/app/shared/phaser/entities/registry/npc.ts
- webapp/src/app/shared/phaser/entities/registry/prop.ts
- webapp/src/app/shared/phaser/entities/registry/scalable-prop.ts
- webapp/src/app/shared/phaser/helper.ts
- webapp/src/app/shared/phaser/main-scene.ts
- webapp/src/app/shared/phaser/tilemap/cc-map-layer.ts
- webapp/src/app/shared/phaser/tilemap/cc-map.ts
depends on #98 
- improves tilemap performance by skipping culling of invisible layers
- images are not preloaded anymore, instead every layer/entity makes sure the image they use is loaded
> improves performance + loading times

- CHANGELOG.md
- webapp/src/app/shared/phaser/entities/cc-entity.ts
- webapp/src/app/shared/phaser/entities/registry/item-destruct.ts
- webapp/src/app/shared/phaser/entities/registry/npc.ts
- webapp/src/app/shared/phaser/entities/registry/prop.ts
depends on #99
Added support for more Prop settings
> improves Prop Entity

- webapp/src/app/components/editor/editor.component.html
- webapp/src/app/components/editor/editor.component.ts
- webapp/src/app/components/load-map/load-map.component.html
- webapp/src/app/components/load-map/load-map.component.scss
- webapp/src/app/components/load-map/load-map.component.ts
- webapp/src/app/components/phaser/phaser.component.ts
- webapp/src/app/shared/phaser/main-scene.ts
load map now only loads all maps on startup or when refresh button is clicked. 
Fixes #74
> Load map refresh

- webapp/src/app/shared/phaser/entities/cc-entity.ts
- webapp/src/app/shared/phaser/entities/registry/npc.ts
- webapp/src/app/shared/widgets/event-widget/event-editor/editor/event-editor.component.ts
- webapp/src/app/shared/widgets/event-widget/event-widget.component.html
- webapp/src/app/shared/widgets/event-widget/event-widget.component.ts
- webapp/src/app/shared/widgets/event-widget/event-window/event-window.component.ts
> Blockevent fix

- parse-action-step.js
- webapp/src/app/shared/widgets/event-widget/event-editor/add/add-event.service.ts
- webapp/src/app/shared/widgets/event-widget/event-editor/detail/event-detail.component.ts
- webapp/src/app/shared/widgets/event-widget/event-editor/editor/event-editor.component.html
- webapp/src/app/shared/widgets/event-widget/event-editor/editor/event-editor.component.ts
- webapp/src/app/shared/widgets/event-widget/event-editor/event-helper.service.ts
- webapp/src/app/shared/widgets/event-widget/event-editor/row-text/row-text.component.ts
- webapp/src/app/shared/widgets/event-widget/event-editor/row/event-row.component.html
- webapp/src/app/shared/widgets/event-widget/event-editor/row/event-row.component.ts
- webapp/src/app/shared/widgets/event-widget/event-registry/abstract-event.ts
- webapp/src/app/shared/widgets/event-widget/event-registry/default-event.ts
- webapp/src/app/shared/widgets/event-widget/event-registry/event-registry.service.ts
- webapp/src/app/shared/widgets/event-widget/event-widget.component.ts
- webapp/src/app/shared/widgets/event-widget/event-window/event-window.component.html
- webapp/src/app/shared/widgets/event-widget/event-window/event-window.component.ts
- webapp/src/app/shared/widgets/widget-registry.service.ts
- webapp/src/assets/actions.json
> added Action widget

- webapp/src/app/components/load-map/load-map.component.html
- webapp/src/app/components/load-map/load-map.component.scss
- webapp/src/app/components/load-map/load-map.component.ts
- webapp/src/app/components/load-map/virtualMapNode.model.ts
> Combine folders with only one subfolder into a singe node in the load-map dialogue

- webapp/src/app/components/layers/layers.component.html
- webapp/src/app/components/layers/layers.component.ts
> Added tileset select

- backend/src/config.ts
- backend/src/server.ts
- common/src/controllers/api.ts
- common/tsconfig.json
- webapp/src/app/components/dialogs/settings/settings.component.html
- webapp/src/app/components/dialogs/settings/settings.component.scss
- webapp/src/app/components/dialogs/settings/settings.component.ts
- webapp/src/app/components/phaser/phaser.component.ts
- webapp/src/app/components/toolbar/toolbar.component.html
- webapp/src/app/components/toolbar/toolbar.component.ts
- webapp/src/app/services/browser.service.ts
- webapp/src/app/services/electron.service.ts
- webapp/src/app/services/http-client.service.ts
- webapp/src/app/services/sharedService.ts
- webapp/src/app/shared/globals.ts
- webapp/src/app/shared/phaser/helper.ts
- webapp/src/app/shared/shared.module.ts
- webapp/src/main.ts
- webapp/tsconfig.json
* Does not work for ccmods
* Fixes #54 
* Closes #156 because custom can only be located inside vanilla or mod folders
> Mod support

- CHANGELOG.md
- webapp/src/app/shared/phaser/tilemap/cc-map.ts
> Fix level heights not being saved as numbers

- CHANGELOG.md
- backend/src/server.ts
- webapp/src/app/components/sidenav/sidenav.component.html
- webapp/src/app/components/sidenav/sidenav.component.ts
- webapp/src/app/models/editor-view.ts
- webapp/src/app/shared/phaser/helper.ts
- webapp/src/app/shared/phaser/main-scene.ts
Fixes #168 
* Changed `Helper.getJson` to return undefined if no file was found.
* Fixed infinite loop in SideNav.
> Npc and freeze fix

- webapp/.editorconfig
- webapp/angular.json
- webapp/package-lock.json
- webapp/package.json
- webapp/src/app/components/phaser/phaser.component.ts
- webapp/src/app/shared/map-loader.service.ts
- webapp/src/app/shared/phaser/entities/cc-entity.ts
- webapp/src/app/shared/phaser/entities/registry/default-entity.ts
- webapp/src/app/shared/phaser/tilemap/cc-map-layer.ts
- webapp/src/app/tests/map-loading.spec.ts
- webapp/src/test.ts
- webapp/src/tsconfig.spec.json
> added map load/export test

- CHANGELOG.md
- webapp/src/app/models/cross-code-map.ts
- webapp/src/app/shared/phaser/entities/cc-entity.ts
- webapp/src/app/shared/phaser/entities/entity-manager.ts
- webapp/src/app/shared/phaser/entities/registry/default-entity.ts
- webapp/src/app/shared/phaser/entities/registry/entity-registry.service.ts
- webapp/src/app/shared/phaser/tilemap/cc-map.ts
- webapp/src/app/tests/entities.spec.ts
- webapp/src/app/tests/test-helper.ts
> generate unique mapId for new entities

- webapp/src/app/shared/phaser/entities/cc-entity.ts
Fixes #180 
Don't ask me how - I don't know either
> Fixed flip offset

- README.md
- updated discord link, closes #184
- added editor image from version 0.8, closes #185
> Update README.md (discord link + image)

- CHANGELOG.md
- webapp/.eslintrc.json
- webapp/src/app/shared/phaser/tilemap/points-in-line.ts
- webapp/src/app/shared/phaser/tilemap/tile-drawer.ts
Improved tile drawing by drawing a line of points instead of a single point. 
Avoids holes when drawing fast.
Fixes #183
> improved tile drawing

- webapp/package-lock.json
- webapp/package.json
- webapp/src/app/components/toolbar/toolbar.component.ts
- webapp/src/app/shared/overlay/overlay-panel/overlay-panel.component.html
- webapp/src/app/shared/overlay/overlay-panel/overlay-panel.component.scss
- webapp/src/app/shared/overlay/overlay-panel/overlay-panel.component.ts
- webapp/src/app/shared/shared.module.ts
- webapp/src/app/shared/split-pane/split-pane.component.html
- webapp/src/app/shared/split-pane/split-pane.component.scss
- webapp/src/app/shared/split-pane/split-pane.component.ts
- webapp/src/app/shared/split-pane/split-pane.module.ts
- webapp/src/app/shared/widgets/event-widget/event-editor/detail/event-detail.component.html
- webapp/src/app/shared/widgets/event-widget/event-editor/detail/event-detail.component.scss
- webapp/src/app/shared/widgets/event-widget/event-editor/detail/event-detail.component.ts
- webapp/src/app/shared/widgets/event-widget/event-editor/editor/event-editor.component.html
- webapp/src/app/shared/widgets/event-widget/event-editor/editor/event-editor.component.ts
- webapp/src/app/shared/widgets/event-widget/event-window/event-window.component.html
- webapp/src/app/shared/widgets/npc-states-widget/npc-states/npc-states.component.html
- webapp/src/app/shared/widgets/npc-states-widget/npc-states/npc-states.component.scss
added resizable event detail and changed styles a bit
> Resizable event details 

- CHANGELOG.md
- webapp/src/app/shared/list-search-overlay/list-search-overlay.component.html
- webapp/src/app/shared/list-search-overlay/list-search-overlay.component.scss
- webapp/src/app/shared/list-search-overlay/list-search-overlay.component.ts
component used in add new entity / add new event
> added keyboard controls (up/down) to list search overlay

- .github/workflows/pull_request.yml
- README.md
we don't use travis ci anymore and the build status for github ci is visible next to the commit hash
> remove build status badge and fix pr check

- CHANGELOG.md
- webapp/src/app/components/load-map/virtualMapNode.model.ts
> Invert load-map directory sort

- CHANGELOG.md
- webapp/src/assets/actions.json
- webapp/src/assets/events.json
This updates event step and action step definitions.
> Event step and action step update

- CHANGELOG.md
- webapp/src/app/components/dialogs/settings/settings.component.html
> Fix typo in settings panel (issue #220)

- CHANGELOG.md
- webapp/src/app/services/phaser/entities/entity-manager.ts
The root cause still needs to be investigated but this should improve it for the time being.
> Temporary fix for double paste

- CHANGELOG.md
- webapp/angular.json
- webapp/src/app/components/layers/layers.component.html
- webapp/src/app/components/sidenav/sidenav.component.html
- webapp/src/app/components/sidenav/sidenav.component.scss
- webapp/src/app/models/cross-code-map.ts
- webapp/src/app/services/phaser/tilemap/cc-map-layer.ts
added `lighter` setting to layer and fixed it's rendering, #261
> layer `lighter` setting

- CHANGELOG.md
- webapp/src/app/components/widgets/enemy-type-widget/enemy-type-widget.component.ts
Warning: Not tested because my setup cant handle old angular.
Resolves #256
> Fix enemyInfo

- CHANGELOG.md
- webapp/src/app/components/entities/entities.component.ts
- webapp/src/app/services/3d/entities/entity-generator.ts
- webapp/src/app/services/3d/entities/entity-manager-3d.ts
- webapp/src/app/services/phaser/entities/cc-entity.ts
- webapp/src/app/services/phaser/entities/entity-manager.ts
- webapp/src/app/services/phaser/entities/registry/event-trigger.ts
- webapp/src/app/services/phaser/entities/registry/npc.ts
After unsuccessfully double clicking an event on instinct for the 10th time I decided to make it a feature.
> Open event and npc editor on double click

- CHANGELOG.md
- webapp/src/app/services/phaser/tilemap/cc-map.ts
> keep layer visiblity when using history undo/redo

- CHANGELOG.md
- webapp/src/app/components/dialogs/offset-map/offset-map.component.html
- webapp/src/app/components/dialogs/offset-map/offset-map.component.ts
- webapp/src/app/components/toolbar/toolbar.component.ts
- webapp/src/app/services/global-events.service.ts
- webapp/src/app/services/phaser/entities/cc-entity.ts
- webapp/src/app/services/phaser/tilemap/cc-map.ts
> added checkbox to "Offset Map" to optionally include entities

- CHANGELOG.md
- webapp/src/app/app.component.ts
- webapp/src/app/app.module.ts
- webapp/src/app/components/dialogs/confirm-close/confirm-close.component.html
- webapp/src/app/components/dialogs/confirm-close/confirm-close.component.scss
- webapp/src/app/components/dialogs/confirm-close/confirm-close.component.ts
- webapp/src/app/components/dialogs/floating-window/history/state-history.service.ts
- webapp/src/app/components/dialogs/load-map/load-map.component.ts
- webapp/src/app/components/dialogs/overlay/overlay-ref-control.ts
- webapp/src/app/components/dialogs/overlay/overlay.service.ts
- webapp/src/app/external-modules/material.module.ts
- webapp/src/app/services/global-events.service.ts
- webapp/src/app/services/save.service.ts
> Added confirm close dialog

- CHANGELOG.md
- webapp/src/app/components/dialogs/load-map/load-map.component.ts
> Reset hasUnsavedChanges on discard

- CHANGELOG.md
- webapp/src/app/services/phaser/entities/cc-entity.ts
duno why but the overriden values in scaleSettings weren't mentioned anywhere so I just mentioned them
fixes #245
solves #291
> Fix entity size overrides
